name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test-node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [10, 12, 13]
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: use node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
      - uses: actions/cache@v1
        id: server-cache
        with:
          path: server/node_modules
          key: ${{ runner.os }}-yarn-${{matrix.node_version}}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.server-cache.outputs.cache-hit != 'true'
        run: yarn install --pure-lockfile
      - run: yarn ci
